"""Regenerate the README results block from analysis/out/results.json.

    .venv/bin/python analysis/render_readme.py

Numbers in the README are never typed by hand. They are rendered from the
results file, and this script refuses to run on simulated results. That is the
enforcement behind "nothing computed from SIMULATED_* reaches README.md".

Everything it prints carries an n and a 95% interval, because a bare point
estimate in a README is how a repo starts lying to its own author.
"""
import json
import os
import re
import sys

BEGIN, END = "<!-- RESULTS:BEGIN -->", "<!-- RESULTS:END -->"
HEADLINE_BEGIN, HEADLINE_END = "<!-- HEADLINE:BEGIN -->", "<!-- HEADLINE:END -->"
LABEL = {"none": "no cue", "filled_pause": "filled pause (“hm”)", "breath": "breath",
         "backchannel": "backchannel (“mm-hm”)", "verbal_stall": "verbal stall (“hang on”)"}
DV_LABEL = {"alive": "aliveness (1–7, higher = more alive)",
            "broken": "seemed broken (1–7, higher = worse)",
            "wait": "would wait again (proportion)"}


def num(v, d=2):
    """v is an {est, ci, n_boot_ok} record, as every estimator returns."""
    return "—" if v.get("est") is None else f"{v['est']:+.{d}f}"


def ci(v, d=2):
    if v.get("ci") is None:
        return "not estimable"
    lo, hi = v["ci"]
    return f"[{lo:+.{d}f}, {hi:+.{d}f}]"


def zero_in(v):
    return v.get("ci") is not None and v["ci"][0] <= 0 <= v["ci"][1]


def verdict(v):
    if v.get("ci") is None:
        return "not estimable"
    return "no detectable effect" if zero_in(v) else "moves it"


def no_data_block(reason):
    return (f"> **Nothing has been analysed yet.** {reason}\n>\n"
            f"> The pipeline is validated by positive and null controls on a simulated\n"
            f"> fixture (`analysis/test_analysis.py`). This section is generated by\n"
            f"> `analysis/render_readme.py` and fills in the moment real ratings exist.\n"
            f"> No number here is hand-typed.\n")


def render(res):
    d, h = res["design"], res["headline"]
    L = []
    L.append(f"**n = {d['n_ratings']:,} ratings** from **{d['n_raters_llm']} LLM judges** "
             f"and **{d['n_raters_human']} human raters**, over **{d['n_stimuli']} clips** "
             f"built from {d['n_exchanges']} dialogue exchanges. Every rating is "
             f"`rater_modality = {', '.join(d['rater_modalities'])}` — the judges read a "
             f"timing description, they did not listen. Intervals are 95% percentile CIs "
             f"from a cluster bootstrap over the {d['n_exchanges']} exchanges "
             f"({res['inputs']['n_boot']:,} resamples).\n")

    L.append("### The dissociation\n")
    L.append("| outcome | a cue, same wait<br>(cue − no cue, 0.8–1.6 s) | +800 ms of wait<br>(1.6 s − 0.8 s) "
             "| +1600 ms of silence<br>(1.6 s − 0 s, no cue) |")
    L.append("|---|---|---|---|")
    for dv in ("alive", "broken", "wait"):
        D = res["dissociation"][dv]
        cells = []
        for key in ("cue_effect", "latency_effect_1600_vs_800",
                    "latency_effect_none_1600_vs_0"):
            v = D[key]
            mark = "" if zero_in(v) else "**"
            cells.append(f"{mark}{num(v)}{mark} {ci(v)}"
                         + (" — includes zero" if zero_in(v) else ""))
        L.append(f"| {DV_LABEL[dv]} | " + " | ".join(cells) + " |")
    L.append("")
    n_cue = res["cue_contrast_matched"]["alive"]["any_cue_vs_none"]
    L.append(f"The cue column is restricted to the 0.8/1.2/1.6 s cells, the only gaps where "
             f"a cued clip and an uncued clip carry the same wait "
             f"({n_cue['a']['n_ratings']} cued ratings over {n_cue['a']['n_stimuli']} clips "
             f"vs {n_cue['b']['n_ratings']} uncued over {n_cue['b']['n_stimuli']}). Below "
             f"800 ms a cue does not fit in the gap, so no such comparison exists.\n")

    L.append("### Latency response, inside `cue = none`\n")
    L.append("| outcome | slope per second of gap | 95% CI | n |")
    L.append("|---|---:|---|---:|")
    for dv in ("alive", "broken", "wait"):
        r = res["latency_response_none"][dv]
        s = r["values"]["slope_per_s"]
        L.append(f"| {DV_LABEL[dv]} | {num(s)} | {ci(s)} | {r['n_ratings']} ratings, "
                 f"{r['n_stimuli']} clips |")
    L.append("")
    L.append("Fitted on `actual_gap_ms`, never on the nominal cell. Inside `cue = none` "
             "the two are identical, so this slope is clean of the cue confound.\n")

    L.append("### Per cue, at matched gaps, on aliveness\n")
    L.append("| cue | aliveness vs no cue | 95% CI | `broken` vs no cue | 95% CI | n |")
    L.append("|---|---:|---|---:|---|---:|")
    pc_a = res["cue_contrast_matched"]["alive"]["per_cue"]
    pc_b = res["cue_contrast_matched"]["broken"]["per_cue"]
    for c, r in sorted(pc_a.items(), key=lambda kv: -kv[1]["values"]["diff"]["est"]):
        a, b = r["values"]["diff"], pc_b[c]["values"]["diff"]
        L.append(f"| {LABEL.get(c, c)} | {num(a)} | {ci(a)} | {num(b)} | {ci(b)} "
                 f"| {r['a']['n_ratings']} vs {r['b']['n_ratings']} |")
    L.append("")
    L.append("Every cue lifts aliveness. None of them changes whether the system "
             "seemed broken. That is the whole result in one table.\n")

    L.append("### Where the variance lives\n")
    L.append("| outcome | what they were shown | who was rating | shared | unexplained |")
    L.append("|---|---:|---:|---:|---:|")
    for dv in ("alive", "broken", "wait"):
        v = res["variance"][dv]
        L.append(f"| {DV_LABEL[dv]} | {v['unique_condition']:.1%} | {v['unique_rater']:.1%} "
                 f"| {v['shared']:.1%} | {v['residual']:.1%} |")
    v = res["variance"]["alive"]
    sp = res["per_rater"]["alive"]["spread"]
    L.append("")
    L.append(f"Commonality analysis on R², {v['n_ratings']:,} ratings, {v['n_raters']} "
             f"personas, {v['n_cells']} design cells (cue × measured gap). The six personas "
             f"were written to disagree — impatient against patient, skeptic against voice "
             f"designer. Their mean aliveness ratings span {sp['range']:.2f} points on a "
             f"7-point scale (SD {sp['sd_of_rater_means']:.2f}). They do not disagree.\n")

    L.append("### The number this repo set out to measure\n")
    L.append(f"**Exchange rate: {h['exchange_rate_ms'] or 'not reported'}.** "
             f"{h['exchange_rate_note']}\n")
    return "\n".join(L)


def headline_line(res):
    h = res["headline"]
    d = res["design"]
    if not h.get("dissociation_supported"):
        return (f"**{h['verdict']}**  \n"
                f"n = {h['n_ratings']:,} ratings, {h['n_raters_llm']} LLM judges, "
                f"{h['n_raters_human']} human raters, {h['n_stimuli']} clips.")
    cue = h["aliveness_cue_effect_matched"]
    sl = h["aliveness_slope_per_s_none"]
    br = h["broken_slope_per_s_none"]
    return (
        f"**LLM judges do not perceive conversational timing. They perceive a cue "
        f"having been described.**  \n"
        f"At the same wait, a non-verbal cue moves rated aliveness by "
        f"**{cue['est']:+.2f}** points on a 7-point scale "
        f"[{cue['ci'][0]:+.2f}, {cue['ci'][1]:+.2f}], while aliveness inside "
        f"`cue = none` is flat against how long the silence actually was "
        f"(**{sl['est']:+.2f}** per second [{sl['ci'][0]:+.2f}, {sl['ci'][1]:+.2f}], "
        f"interval spans zero). The same silences do move *seemed broken* "
        f"(**{br['est']:+.2f}** per second [{br['ci'][0]:+.2f}, {br['ci'][1]:+.2f}]), "
        f"so this is a dissociation, not a judge that ignores everything.  \n"
        f"n = {h['n_ratings']:,} ratings, {h['n_raters_llm']} LLM judges, "
        f"{h['n_raters_human']} human raters, {h['n_stimuli']} clips, "
        f"{d['n_exchanges']} exchanges.")


def splice(text, begin, end, body):
    pat = re.compile(re.escape(begin) + r".*?" + re.escape(end), re.S)
    if not pat.search(text):
        sys.exit(f"README is missing the {begin} ... {end} markers")
    return pat.sub(lambda _: f"{begin}\n{body}\n{end}", text)


def main():
    results = sys.argv[1] if len(sys.argv) > 1 else "analysis/out/results.json"
    readme = "README.md"
    if not os.path.exists(results):
        body = no_data_block(f"`{results}` does not exist yet.")
        head = "**No headline yet — the analysis has not been run.**"
    else:
        res = json.load(open(results))
        if res.get("simulated"):
            sys.exit("REFUSING: these are SIMULATED results. Simulated numbers must never "
                     "reach README.md. Run analysis/run.py on data/ratings.jsonl instead.")
        if res["design"]["n_ratings"] == 0:
            body = no_data_block("There are no ratings in `data/ratings.jsonl` yet.")
            head = "**No headline yet — there is nothing to analyse.**"
        else:
            body, head = render(res), headline_line(res)

    text = open(readme).read()
    text = splice(text, HEADLINE_BEGIN, HEADLINE_END, head)
    text = splice(text, BEGIN, END, body)
    open(readme, "w").write(text)
    print(f"README results block rendered from {results}")


if __name__ == "__main__":
    main()
