"""Inline the stimulus manifest into web/stimuli.js.

    .venv/bin/python web/build.py

web/rate.html has to work when you double-click it, and file:// blocks
fetch() of a local .jsonl in Chrome. A classic <script> tag is not blocked, so
the manifest ships as JS instead of being fetched.

Only the fields the page needs: no prompt/response text, because the rater
should be listening rather than reading ahead.
"""

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "data", "stimuli.jsonl")
OUT = os.path.join(ROOT, "web", "stimuli.js")

KEEP = ("stim_id", "latency_ms", "cue", "exchange_id", "wav_path",
        "actual_gap_ms")

with open(SRC) as f:
    rows = [json.loads(l) for l in f if l.strip()]

slim = [{k: r[k] for k in KEEP} for r in rows]
with open(OUT, "w") as f:
    f.write("// generated by web/build.py -- do not edit\n")
    f.write("window.STIMULI = ")
    json.dump(slim, f, separators=(",", ":"))
    f.write(";\n")

cells = {(r["latency_ms"], r["cue"]) for r in slim}
print(f"{len(slim)} stimuli, {len(cells)} cells -> web/stimuli.js")
